spring:
  application:
    name: popfigure
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=PopFigureDB;encrypt=true;trustServerCertificate=true}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:Phu@232005}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.SQLServerDialect
  sql:
    init:
      mode: never

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.web: info

jwt:
  signerKey: "YrEVJT18ZbsjODUVwuXjY82aGttLRFfpk0PVyFWDfER"
